/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wanghongjun_android_ndk_demo_Demo_DemoHelper */

#ifndef _Included_com_example_wanghongjun_android_ndk_demo_Demo_DemoHelper
#define _Included_com_example_wanghongjun_android_ndk_demo_Demo_DemoHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wanghongjun_android_ndk_demo_Demo_DemoHelper
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wanghongjun_android_1ndk_1demo_Demo_DemoHelper_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
